<?php
/* NEWSTITLES CONFIGURATION OPTIONS */
$_NEWSTITLES_CFG = Array();
#[en]USE JQUERY-UI STYLING (RECOMMENDED ONLY FOR JQUERY-UI THEMES) {1=YES,0=NO}
#[it]USA STILE JQUERY-UI (CONSIGLIATO SOLO PER TEMI JQUERY-UI) {1=SI,0=NO}
$_NEWSTITLES_CFG['use-jqueryui'] = 1;
#[en]SHOW TOP BOX WITH MOST RECENT NEWS {1=YES,0=NO}
#[it]MOSTRA BOX SUPERIORE CON LA NOTIZIA PIU' RECENTE {1=SI,0=NO}
$_NEWSTITLES_CFG['use-topbox'] = 1;
?> 